#!/bin/bash
# Generate a PowerShell script that recreates all project files
OUTPUT="/home/user/setup-project.ps1"

echo '$ErrorActionPreference = "Stop"' > "$OUTPUT"
echo '$utf8 = New-Object System.Text.UTF8Encoding $false' >> "$OUTPUT"
echo '' >> "$OUTPUT"
echo '# Create directory structure' >> "$OUTPUT"
echo '$dirs = @(' >> "$OUTPUT"
echo '    "MigrationScheduler/MigrationScheduler.Blazor/Pages",' >> "$OUTPUT"
echo '    "MigrationScheduler/MigrationScheduler.Blazor/Components",' >> "$OUTPUT"
echo '    "MigrationScheduler/MigrationScheduler.Blazor/Models",' >> "$OUTPUT"
echo '    "MigrationScheduler/MigrationScheduler.Blazor/Services",' >> "$OUTPUT"
echo '    "MigrationScheduler/MigrationScheduler.Blazor/Shared",' >> "$OUTPUT"
echo '    "MigrationScheduler/MigrationScheduler.Blazor/Properties",' >> "$OUTPUT"
echo '    "MigrationScheduler/MigrationScheduler.Blazor/wwwroot/css",' >> "$OUTPUT"
echo '    "MigrationScheduler/MigrationScheduler.Blazor/wwwroot/js",' >> "$OUTPUT"
echo '    "MigrationScheduler/MigrationScheduler.Host"' >> "$OUTPUT"
echo ')' >> "$OUTPUT"
echo 'foreach ($d in $dirs) { New-Item -ItemType Directory -Force -Path $d | Out-Null }' >> "$OUTPUT"
echo 'Write-Host "Directories created."' >> "$OUTPUT"
echo '' >> "$OUTPUT"

# Function to add a file to the PS1 script
add_file() {
    local filepath="$1"
    local ps_path="MigrationScheduler/${filepath}"
    
    echo "" >> "$OUTPUT"
    echo "# --- $ps_path ---" >> "$OUTPUT"
    echo "\$content = @'" >> "$OUTPUT"
    cat "$filepath" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "'@" >> "$OUTPUT"
    echo "[System.IO.File]::WriteAllText(\"\$PSScriptRoot/$ps_path\", \$content, \$utf8)" >> "$OUTPUT"
}

cd /home/user/MigrationScheduler

# Add every file
add_file "MigrationScheduler.sln"
add_file "MigrationScheduler.Blazor/MigrationScheduler.Blazor.csproj"
add_file "MigrationScheduler.Blazor/Program.cs"
add_file "MigrationScheduler.Blazor/App.razor"
add_file "MigrationScheduler.Blazor/_Imports.razor"
add_file "MigrationScheduler.Blazor/appsettings.json"
add_file "MigrationScheduler.Blazor/appsettings.Development.json"
add_file "MigrationScheduler.Blazor/Properties/launchSettings.json"
add_file "MigrationScheduler.Blazor/Pages/_Host.cshtml"
add_file "MigrationScheduler.Blazor/Pages/ProjectSetup.razor"
add_file "MigrationScheduler.Blazor/Pages/ActivityEditor.razor"
add_file "MigrationScheduler.Blazor/Pages/ConstraintManager.razor"
add_file "MigrationScheduler.Blazor/Pages/ExportPage.razor"
add_file "MigrationScheduler.Blazor/Shared/MainLayout.razor"
add_file "MigrationScheduler.Blazor/Components/MigrationTypeSelector.razor"
add_file "MigrationScheduler.Blazor/Components/PrerequisiteWarning.razor"
add_file "MigrationScheduler.Blazor/Components/TaskGrid.razor"
add_file "MigrationScheduler.Blazor/Components/GanttPreview.razor"
add_file "MigrationScheduler.Blazor/Models/MigrationType.cs"
add_file "MigrationScheduler.Blazor/Models/TaskConstraint.cs"
add_file "MigrationScheduler.Blazor/Models/PredecessorLink.cs"
add_file "MigrationScheduler.Blazor/Models/TaskModel.cs"
add_file "MigrationScheduler.Blazor/Models/ProjectModel.cs"
add_file "MigrationScheduler.Blazor/Services/ProjectStateService.cs"
add_file "MigrationScheduler.Blazor/Services/PrerequisiteValidator.cs"
add_file "MigrationScheduler.Blazor/Services/TaskTemplateService.cs"
add_file "MigrationScheduler.Blazor/Services/DraftService.cs"
add_file "MigrationScheduler.Blazor/Services/XmlExportService.cs"
add_file "MigrationScheduler.Blazor/wwwroot/css/app.css"
add_file "MigrationScheduler.Blazor/wwwroot/js/interop.js"
add_file "MigrationScheduler.Host/MigrationScheduler.Host.csproj"
add_file "MigrationScheduler.Host/Program.cs"
add_file "MigrationScheduler.Host/MainForm.cs"
add_file "README.md"
add_file ".gitignore"

echo '' >> "$OUTPUT"
echo 'Write-Host ""' >> "$OUTPUT"
echo 'Write-Host "All 35 files created successfully in MigrationScheduler/" -ForegroundColor Green' >> "$OUTPUT"
echo 'Write-Host "Next steps:"' >> "$OUTPUT"
echo 'Write-Host "  git add MigrationScheduler/"' >> "$OUTPUT"
echo 'Write-Host "  git commit -m ''Add Honeywell Experion Migration Project Scheduler''"' >> "$OUTPUT"
echo 'Write-Host "  git push -u origin main"' >> "$OUTPUT"

